import Document, { Html, Head, Main, NextScript } from 'next/document';
class MyDocument extends Document {
  render() {
    return (
      <Html lang="en" className="scroll-smooth">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Fredoka:wght@400;600&display=swap"
            rel="stylesheet"
          />
          <meta name="viewport" content="viewport-fit=cover" />

          <meta property="og:url" content="https://www.arcodesolucoes.com/" />
          <meta property="og:type" content="site_name" />
          <meta
            property="og:title"
            content="Arcode, Criação de site para seu negócio."
          />
          <meta
            property="og:description"
            content="Arcode ajuda alavancar suas vendas através da criação de seu site para seu negócio."
          />
          <meta property="og:image" content="https://i.imgur.com/8Q825KL.png" />

          <meta
            name="keywords"
            content="site,fazer,criar,arcode,fazer,plataforma,ecommerce,vendas,soluções,orçamento,seo"
          />
          <meta name="author" content="Arthur Rocha" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
